schema_version: 1

context:
  version: "1.2.0"

package:
  name: molsym
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/molsym/molsym-${{ version }}.tar.gz
  sha256: dcd894ac8c14c02ac305ef48a6e7bf152414db8ac0c93a21c3638433c6971bc0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.23.4

tests:
  - python:
      imports:
        - molsym
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A program for molecular symmetry detection and SALC construction
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/NASymmetry/MolSym
  documentation: https://molsym.readthedocs.io

extra:
  recipe-maintainers:
    - nlk36701
