schema_version: 1

context:
  version: "1.1.1"

package:
  name: molsym
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/molsym/molsym-${{ version }}.tar.gz
  sha256: 591cd86b3e1354d31340c747523ba813557ccb2fe2bcb4cab1c6d98ba835a655

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.23.4

tests:
  - python:
      imports:
        - molsym
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A program for molecular symmetry detection and SALC construction
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/NASymmetry/MolSym
  documentation: https://molsym.readthedocs.io

extra:
  recipe-maintainers:
    - nlk36701
